version: "3"

services:
  api:
    build: .
    environment:
      TENSORFLOW_SERVING_URL: "http://tf-serving"
      TENSORFLOW_SERVING_PORT: "8501"
      TENSORFLOW_SERVING_MODEL_NAME: "my_production_model"
      TENSORFLOW_SERVING_MODEL_PATH: "v1/models"
      QDRANT_URL: "qdrant"
      QDRANT_PORT: "6333"
      QDRANT_COLLECTION_NAME: "CharactersVectors"
    ports:
      - "8000:8000"
    depends_on:
      - tf-serving
      - qdrant

  tf-serving:
    image: tensorflow/serving:2.8.0
    environment:
      MODEL_NAME: my_production_model
    ports:
      - "8500:8500"
      - "8501:8501"
    volumes:
      - ./storage/models/my_production_model:/models/my_production_model/1/

  qdrant:
    image: generall/qdrant
    environment:
      RUST_BACKTRACE: "1"
    volumes:
      - ./storage/qdrant/storage:/qdrant/storage
      - ./qdrant_config.yaml:/qdrant/config/production.yaml
    ports:
      - "6333:6333"
