logging:
  config:
    path: ${APP_PATH}/default_logging.ini

tensorflow_serving:
  url: ${TENSORFLOW_SERVING_URL}
  model:
    name: ${TENSORFLOW_SERVING_MODEL_NAME}
    path: ${TENSORFLOW_SERVING_MODEL_PATH}

qdrant:
  url: ${QDRANT_SERVER_URL}
  port: ${QDRANT_SERVER_PORT}
  collection_name: ${QDRANT_SERVER_COLLECTION_NAME}
